### ISSUE TITLE
Compatibility certification request for Weld

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi#410]
- [*] Organization Name ("Organization") and, if applicable, URL
Red Hat, Inc., http://redhat.com
- [*] Product Name, Version and download URL (if applicable)
Weld 3.1.1.Final, https://weld.cdi-spec.org/download/
- [*] Specification Name, Version and download URL
Jakarta Contexts Dependency Injection 2.0
- [*] TCK Version, digital SHA-256 fingerprint and download URL
http://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip, 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808
- [*] Public URL of TCK Results Summary
https://github.com/jakartaredhat/weld-cdi-tck/wiki
- [*] Java runtime used to run the implementation
Oracle Runtime Environment java version "1.8.0_211" Java™ SE Runtime Environment (build 1.8.0_211-b12) Java HotSpot™ 64-Bit Server VM (build 25.211-b12, mixed mode)
- [*] Summary of the information for the certification environment, operating system, cloud,
Think pad, 18.04.1-Ubuntu
- [*] By checking this box I acknowledge that I accept the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [*] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
The TCK link should point to the final promoted TCK: 
https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip

**Comment by starksm64** [comment]
Links updated
