### ISSUE TITLE
Correct Javadoc for generation with xdoclint

### ISSUE THREAD

**Issue by antoinesd** [eclipse-ee4j/cdi#422]
Javadoc generation requires Xdoclint to be turned deactivated: 

`mvn javadoc:javadoc -DadditionalJOption=-Xdoclint:none`

We should review all Javadoc to fix issue preventing the use of Xdoclint

**Comment by manovotn** [comment]
Does `-DadditionalJOption=-Xdoclint:none` actually work for you?
Because just today I bumped into a similar problem in CDI TCK repo and the option seems to have been ignored...
Though I also updated the plugin to `3.1.1`, not sure what version is in this repo.

**Comment by antoinesd** [comment]
Yes it works. The release is stuck by authorization issue in sonatype repo.

**Comment by starksm64** [comment]
I have cleaned up the errors in both the 3.0 branch and master so that the -Xdoclint override is no longer needed.
