### ISSUE TITLE
Make beans.xsd available under the new namespace

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/cdi#440]
https://jakarta.ee/xml/ns/jakartaee/#9

**Comment by starksm64** [comment]
There is a PR to do this:
https://github.com/jakartaee/jakarta.ee/pull/850

**Comment by scottmarlow** [comment]
Can this issue be closed now that https://github.com/jakartaee/jakarta.ee/pull/850 was merged?

**Comment by starksm64** [comment]
Yes.
