### ISSUE TITLE
Complete steps for CDI 3.0

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/cdi#448]
* Specification Committee Mentor... 
- [x] creates an issue in the specification project that includes the following checklist for the specification project team:

 ----
* Specification Project Team
 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by dansiviter** [comment]
It seems there is a [3.0.0](https://repo1.maven.org/maven2/jakarta/enterprise/jakarta.enterprise.cdi-api/3.0.0/) build in Maven central, but this repo neither has a 3.0.0 tag nor has been updated to 3.0.1-SNAPSHOT. That doesn't seem to be the case for other specs such as [JAX-RS](/eclipse-ee4j/jaxrs-api/releases/tag/3.0.0) or [JPA](/eclipse-ee4j/jpa-api/releases/tag/3.0-3.0.0-RELEASE). I assume it's just an oversight?

**Comment by starksm64** [comment]
3.0.0 tag was added pointing to 5c59e423662505beecc10093710e5834b68ba2b3 to match the release build:
https://ci.eclipse.org/cdi/job/CDI%20Release/37/
