### ISSUE TITLE
Please tag version used for release 3.0.0

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/cdi#465]
There is https://repo.maven.apache.org/maven2/jakarta/enterprise/jakarta.enterprise.cdi-api/3.0.0/ published.
May I ask to tag the version that was used to produce this release, please?

**Comment by pzygielo** [comment]
I have tag
```
tag 3.0.0
Tagger:     Scott M Stark
TaggerDate: Wed Aug 26 16:48:30 2020 -0500

Move 3.0.0 tag
```
for commit 5c59e423662505beecc10093710e5834b68ba2b3, which seems to be deleted in this repository, and I can't see replacement.

**Comment by manovotn** [comment]
I don't see a reason why anyone would delete it.
@starksm64 this should be done automatically via release in Jenkins, right? Do you remember deleting some tags for any reason?

**Comment by pzygielo** [comment]
> I don't see a reason why anyone would delete it.

Deletion happened before Mon 31 Aug 10:23:02 CEST 2020.

> @starksm64 this should be done automatically via release in Jenkins, right? Do you remember deleting some tags for any reason?

It seems tags in this repo are not created by bots/Jenkins, but by humans rather.

**Comment by starksm64** [comment]
Yes, the staging release process should be creating the tag. I'll look into why it could be missing.

**Comment by starksm64** [comment]
3.0.0 tag has been added to 5c59e423662505beecc10093710e5834b68ba2b3 to match the 3.0.0 release build:
https://ci.eclipse.org/cdi/job/CDI%20Release/37/
