### ISSUE TITLE
Split Spec doc to introduce CDI Lite

### ISSUE THREAD

**Issue by antoinesd** [eclipse-ee4j/cdi#468]
Since working group agreed to make CDI Lite a subset of CDI core, we need to organize the spec to introduce CDI Lite in it.
New organization should split the current _core_ part in _CDI Lite_ and _CDI Full_ subparts.

**Comment by manovotn** [comment]
The PR for this is now merged, so closing this issue.
Follow up issues are tracked under https://github.com/eclipse-ee4j/cdi/issues/482
