### ISSUE TITLE
Spliting BeanManager for CDI Lite

### ISSUE THREAD

**Issue by antoinesd** [eclipse-ee4j/cdi#469]
We should create a new BM interface containing methods supported by lite only.
The current BM would be accessible by extending this lighter BM and add the missing methods for Full.

**Comment by manovotn** [comment]
I have sent a draft of what it could look like. I suppose we'll discuss it in the next meeting (23rd March) and OFC any feedback on the PR or here is welcome as well.

**Comment by manovotn** [comment]
Solved via https://github.com/eclipse-ee4j/cdi/pull/471.
We can adjust it further if needed but we want something in to be able to cut first Alpha releases.
