### ISSUE TITLE
Provide default wrappers for classes like AnnotatedType and AnnotatedMethod

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/cdi#480]
CDI extensions allow us to add a new annotated type. 

A typical use case is to programmatically add or remove annotations to/from existing types, which makes the usage of wrappers necessary. CDI does not provide default wrappers, so projects often need to recreate these. While not difficult, it's tedious and error prone. 

Just like APIs like e.g. Servlet and Faces, it would be good if CDI provided a few default wrappers here.

**Comment by Ladicek** [comment]
I think you're refering to the "older" extension API, which indeed require you to implement the entire `AnnotatedType` / `AnnotatedMethod` / ... interface. There's a "newer" API that is much easier to use for cases like yours: `AnnotatedTypeConfigurator` / `AnnotatedMethodConfigurator` / ... Usually, wherever there's a way to set `AnnotatedType`, there's also a way to get an `AnnotatedTypeConfigurator` for given class -- I'd definitely recommend using that.

**Comment by manovotn** [comment]
Why not use the configurator API? Doesn't it do precisely what you want without having to create a wrapper?
E.g. [`AnnotatedTypeConfigurator`](https://github.com/eclipse-ee4j/cdi/blob/master/api/src/main/java/jakarta/enterprise/inject/spi/configurator/AnnotatedTypeConfigurator.java) and its variants for methods/fields/params.

**Comment by arjantijms** [comment]
@Ladicek @manovotn you're both right, the typical use case I mentioned doesn't need wrappers of course when using the configurator API. I had a more advanced case in mind, but I guess the brain short-circuited when writing the issue 🤐

**Comment by manovotn** [comment]
So is this issue still needed or can we close it?

**Comment by arjantijms** [comment]
I went back over my notes for which I wanted to create the issue in the first place. Perhaps the use case is, in hindsight, a little too obscure. The configurator is enough for the trivial cases, and for who needs more, they can create the wrapper themselves.

Okay, let's close this then. Sorry for the noise (I'm working through a backlog of "to be created issues", so there are some more coming ;))
