### ISSUE TITLE
Lite/Full split: define packaging/deployment/lifecycle

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#483]
https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/packagingdeployment_lite.asciidoc

This also affects the "The `BeanContainer` object" chapter:

https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/beanmanager_lite.asciidoc

It also affects the "Modularity" chapter:

https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/injectionandresolution.asciidoc

**Comment by manovotn** [comment]
Was resolved some time ago as part of https://github.com/eclipse-ee4j/cdi/pull/546 (and other PRs), we just forgot to close the issue.
Closing now...
