### ISSUE TITLE
Lite/Full split: decide on passivation mentions in the CDI Lite spec part

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#486]
There's a lot of mentions of passivation concepts in the CDI Lite specification part. We need to decide what to do with them: move to Full, leave them where they are?

List of places:

- https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/events.asciidoc
- https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/injectionandresolution.asciidoc
- https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/scopescontexts.asciidoc

**Comment by manovotn** [comment]
I think I already moved some passivation-related bits in other PRs. I'll assign myself and take a look at what TODOs are left WRT passivation.
