### ISSUE TITLE
Lite/Full split: decide on "The `EventMetadata` interface"

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#493]
The "The `EventMetadata` interface" chapter has a TODO for deciding whether we should mention `BeanManager.getEvent()` or `BeanContainer.getEvent()`.

https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/events.asciidoc

**Comment by manovotn** [comment]
Since `getEvent()` is now on `BeanContainer`, we should mention that one instead.
