### ISSUE TITLE
Lite/Full split: decide on "Defining new scope types"

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#494]
The "Defining new scope types" chapter has a TODO about allowing `@Priority` on stereotypes. This should be decided separately, out of the Lite/Full split. The TODO itself can/should be removed without action.

https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/core/definition.asciidoc

**Comment by Ladicek** [comment]
I have filed #495 for deciding whether we want to allow `@Priority` on stereotypes or not. As I said, the TODO for this (that I added during Lite/Full split) can/should be removed without action, as this decision is unrelated to Lite/Full split.

**Comment by manovotn** [comment]
This can probably be closed as https://github.com/eclipse-ee4j/cdi/pull/524 will address it but I'll let @Ladicek be the judge of that :)

**Comment by Ladicek** [comment]
I'd treat this issue as "we should remove the TODO comment" :-)
