### ISSUE TITLE
Update CI setup

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/cdi#502]
This project used Travis but apparently never migrated to the new variant which means the CI now doesn't work.

We should fix that.
Personally, I'd just add GH actions for which I can send a PR.

**Comment by Ladicek** [comment]
Should it use something provided by Eclipse? I have no idea how that works, just wondering. GH Actions are simplest for sure :-)

**Comment by Ladicek** [comment]
Sounds good then! :-)
