### ISSUE TITLE
Portable Extension's `ObserverMethod` doesn't expose the declaring `Bean`

### ISSUE THREAD

**Issue by Ladicek** [eclipse-ee4j/cdi#563]
The Build Compatible Extension API has a method `ObserverInfo.bean()` that provides access to the _bean_ that declares given observer. The Portable Extension API only has `ObserverMethod.getBeanClass()` (providing access to the _class_ that declares given observer).

To keep BCExtensions a strict subset of PExtensions, either we have to remove `ObserverInfo.bean()`, or add `ObserverMethod.getDeclaringBean()` (copying the name from Weld's `ObserverMethodImpl`, which does expose the declaring bean).

**Comment by manovotn** [comment]
@Ladicek do we need this in CR?
