### ISSUE TITLE
BeanContainer#getInjectableReference should probably be on BeanManager instead

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/cdi#568]
`BeanContainer` API currently houses `getInjectableReference(InjectionPoint ij, CreationalContext<?> ctx)` which was originally on `BeanManager`.

After some discussion with @Ladicek we arrived at the conclusion that this doesn't make much sense.
In Lite, you don't have access (via `BeanContainer`) to programmatic creation of `InjectionPoint` because that's based off the former metadata model (`AnnotatedType` and friend). You cannot store them from extensions either so your means of getting hold of them are very limited. Possibly only to creating a class directly implementing an IP which, again, requires usage of the `Annotated*` metamodel.

Therefore, we should move this method back to `BeanManager`.
Note that recently we changed the wording so that implementations in Lite are allowed to support `BeanManager` in some limited form as well meaning that if this functionality turns out to be needed, it can still be implemented without breaking spec compatibility.

**Comment by Ladicek** [comment]
Technically, we don't "allow Lite implementations to support `BeanManager` in some limited form". We require Lite implementations to provide an implementation of `BeanManager` when they're asked for it, but invoking any method that doesn't come from `BeanContainer` is non-portable.

**Comment by manovotn** [comment]
> Technically, we don't "allow Lite implementations to support BeanManager in some limited form".

True, I was to lazy to search for exact wording in the spec :)
