### ISSUE TITLE
CDI Lite TCK compatiple implementation

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi#583]
We need to have an implementation of CDI Lite passing its TCK. I started a prototype lite-tck-runner module similar to the inject-tck-runner module in weld core. Currently it runs, but it is not actually calling out the LangModelVerifierExtension.run method. From the https://github.com/starksm64/core.gi

```
└> cd lite-tck-runner
└> mvn -Pstaging test
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.weld.lite.tck.LiteTCK
LangModelVerifierExtension.ctor
Dec 11, 2021 9:12:42 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 5.0.0 (2021-12-11 14:53)
Dec 11, 2021 9:12:44 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Dec 11, 2021 9:12:44 AM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] public org.jboss.weld.lite.extension.translator.LiteExtensionTranslator.enhancement(@Priority @Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
TestBean was created
TestBean.instance: org.jboss.weld.lite.tck.TestBean@94f6bfb
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.474 s - in org.jboss.weld.lite.tck.LiteTCK
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.788 s
[INFO] Finished at: 2021-12-11T09:12:46-06:00
[INFO] ------------------------------------------------------------------------
```

I see the LangModelVerifierExtension ctor called, but the run method is not. A little debugging shows the LiteExtensionTranslator processing the LangModelVerifierExtension, but fails to call the run method in ExtensionPhaseBase even though the method is found.

**Comment by manovotn** [comment]
Aah, I completely forgot to add the lang-model TCK there. I can look into that on Mon.

I am not sure how you set up that deployment and test but the simplest thing would be to use either Weld SE or Weld embedded (which is used for TCK runs by default) and add the extension there.

> but fails to call the run method in ExtensionPhaseBase even though the method is found.

Hmm, I'd guess this is because it will only be notified for `types = LangModelVerifier.class` and there are none discovered.
Just from the top of my head, that could be something related to how the test archive is structures and what discovery is used (because `LangModelVerifier` doesn't have bean defining anntoation).
As a quick hack, you could try to register that bean via extensions. Add this into your existing extension:
```
    @Discovery
    public void discovery(ScannedClasses scan) {
        scan.add(LangModelVerifier.class.getName());
    }
```

**Comment by starksm64** [comment]
Ok, I followed the at inject model which does setup a TestContainer with the SE envrionment and a BeansXml instance with the all discovery mode. I added your hack and this does get the LangModelVerifierExtension.run method to be called:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.jboss.weld.lite.tck.LiteTCK
LangModelVerifierExtension.ctor
Dec 11, 2021 10:04:02 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 5.0.0 (2021-12-11 14:53)
Dec 11, 2021 10:04:03 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Dec 11, 2021 10:04:03 PM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] public org.jboss.weld.lite.extension.translator.LiteExtensionTranslator.enhancement(@Priority @Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Begin LangModelVerifierExtension.run
LangModelVerifier succeeded
End LangModelVerifierExtension.run
TestBean was created
TestBean.instance: org.jboss.weld.lite.tck.TestBean@606fc505
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.445 s - in org.jboss.weld.lite.tck.LiteTCK
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.122 s
[INFO] Finished at: 2021-12-11T22:04:04-06:00
[INFO] ------------------------------------------------------------------------
```

There is no output from the `LangModelVerifier.verify(clazz)` call. It would be nice if it at least printed out a pass/fail message, but technically it would seem the lite-tck-runner verifies that Weld passes.

**Comment by manovotn** [comment]
> so it would seem the lite-tck-runner verifies that Weld passes.

Yea, me and Ladislav tested this, I just forgot to add it to the Weld as a profile/module. I'll do it for the next version.

> The CDI Language Model TCK doc is very open about how the verify method is called, so technically this is done.

+1

**Comment by manovotn** [comment]
@starksm64 just an FYI
Weld issue - https://issues.redhat.com/browse/WELD-2699
PR - https://github.com/weld/core/pull/2617

The way I set that up means it will automatically execute these TCKs with every `mvn clean install` you do on the project. Obviously, it can also be executed manually.

**Comment by manovotn** [comment]
Hmm, I'm seeing something weird with JDK 16.
Following TCK assertion is failing for me on JDK 16 but works with JDK 11 - https://github.com/eclipse-ee4j/cdi-tck/blob/master/lang-model/src/main/java/org/jboss/cdi/lang/model/tck/AnnotatedTypes.java#L633

Weld impl which I am seeing this with uses reflection to access underlying types and apparently there is different information on JDK 11 and 16.
However, from common sense, I'd say that the assertion is incorrect (and so is the JDK 11 reflection information) because the type variable `B` has in fact a bound that is annotated as seen [here](https://github.com/eclipse-ee4j/cdi-tck/blob/master/lang-model/src/main/java/org/jboss/cdi/lang/model/tck/AnnotatedTypes.java#L265). Or am I missing something @graemerocher @starksm64 ?

**Comment by manovotn** [comment]
With some more trying and testing, this looks like a JDK issue.
Performing the following from within debug:

> `((AnnotatedTypeFactory.AnnotatedTypeVariableImpl) AnnotatedTypes.class.getDeclaredField("typeVariableField").getAnnotatedType()).getAnnotatedBounds()`

JDK 11 gives you just type `A`.
Whereas JDK 16 gives you `@org.jboss.cdi.lang.model.tck.AnnTypeVariableClass3() A`.

I know @Ladicek mentioned he encountered similar problem elsewhere so he might have some insight but he's on PTO right now. Either way, this specific functionality doesn't anyhow block CDI as we do not use this part of lang model.

Tomorrow I'll create a CDI-TCK issue and send a PR that comments out these conflicting bits (as I suppose there might be multiple corner cases). I also aim to test other JDK versions to see the outcomes there.

**Comment by graemerocher** [comment]
yeah I have no comment on this because we don't use this APIs but use the APT equivalents

**Comment by manovotn** [comment]
> yeah I have no comment on this because we don't use this APIs but use the APT equivalents

@graemerocher I guess my question was more along the lines of whether you're able to execute lang model TCKs without problem with various JDK versions. I don't have much experience with APT equivalents, so I don't know if it's prone to these kinds of problems or not :)

**Comment by manovotn** [comment]
This has been resolved some iterations ago and the issue can be closed (Weld is passing it).
