### ISSUE TITLE
issue management url in published POM is dead

### ISSUE THREAD

**Issue by Vampire** [eclipse-ee4j/cdi#588]
The published POM of `4.0.0.Beta3` contains
```xml
<issueManagement>
    <system>JIRA</system>
    <url>https://jira.jboss.org/browse/CDI</url>
</issueManagement>
```
but following that URL just leads to:
![grafik](https://user-images.githubusercontent.com/325196/149682749-8a86e5b6-5ace-4aca-87fd-ee8e5e6d7042.png)

**Comment by starksm64** [comment]
Updated to https://github.com/eclipse-ee4j/cdi/issues
