### ISSUE TITLE
maven-metadata.xml on Maven Central is outdated and incomplete

### ISSUE THREAD

**Issue by Vampire** [eclipse-ee4j/cdi#589]
The `maven-metadata.xml` for `jakarta.enterprise:jakarta.enterprise.cdi-api`on Maven Central lists only version `2.0.1` and also defines `2.0.1` as the `latest` version and `release` version.
This confuses tools that allow to check for version updates or use dynamic version declarations.
The `maven-metadata.xml` should list all versions that are present in the repository and also have `latest` and `release` fields properly set.

**Comment by starksm64** [comment]
My search on https://search.maven.org/artifact/jakarta.enterprise/jakarta.enterprise.cdi-api produces the following view which shows 4.0.0.Beta3-2.0.x, so I'm not sure how you are coming up with that set of versions which is now 3+ years old.

![maven-central-cdi](https://user-images.githubusercontent.com/332210/149684809-d440ec8c-2e64-4840-8ee6-103b253b675c.png)

**Comment by pzygielo** [comment]
Indeed - https://repo.maven.apache.org/maven2/jakarta/enterprise/jakarta.enterprise.cdi-api/maven-metadata.xml has only 2.0.1 listed.

Needs to be reported with https://issues.sonatype.org/

**Comment by starksm64** [comment]
It has been reported: https://issues.sonatype.org/browse/MVNCENTRAL-7257

**Comment by pzygielo** [comment]
Hi @starksm64 - as [MVNCENTRAL-7257](https://issues.sonatype.org/browse/MVNCENTRAL-7257) is not public - what's the status of it? https://repo.maven.apache.org/maven2/jakarta/enterprise/jakarta.enterprise.cdi-api/maven-metadata.xml is still or again listing just 2.0.1.

**Comment by starksm64** [comment]
They said it had been updated, but when I checked I was also seeing the same contents. I have posted that on the issue.
