### ISSUE TITLE
Missing copyright headers on the new BCE

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse-ee4j/cdi#597]
The new classes under https://github.com/eclipse-ee4j/cdi/tree/master/api/src/main/java/jakarta/enterprise/inject/build/compatible/spi have no copyright header.

**Comment by Emily-Jiang** [comment]
I will find out whether it is mandatory to have the copyright headers as I have not seen Jakarta EE API classes without any copyright headers.

**Comment by pzygielo** [comment]
Perhaps https://www.eclipse.org/projects/handbook/#ip-copyright-headers is applicable 
> Where possible, all source code [...] should contain appropriate copyright

**Comment by Emily-Jiang** [comment]
Thank you @pzygielo for the link! I talked with @ivargrimstad and he confirmed that the new classes need to have copyright headers. I guess the following copyright template might work. More details can be found from the link provided by @pzygielo 

> /********************************************************************************
>  * Copyright (c) {year} {owner}[ and others]
>  *
>  * This program and the accompanying materials are made available under the
>  * terms of the Eclipse Public License 2.0 which is available at
>  * http://www.eclipse.org/legal/epl-2.0, or the Apache Software License 2.0
>  * which is available at https://www.apache.org/licenses/LICENSE-2.0.
>  *
>  * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
>  ********************************************************************************/

**Comment by starksm64** [comment]
This has been added via #598
