### ISSUE TITLE
Clarify handling exceptions during async events

### ISSUE THREAD

**Issue by manovotn** [eclipse-ee4j/cdi#599]
The specification [has a chapter on this](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#async_exception) but it is IMO not entirely clear because it only covers the case where more than one exception is thrown.

The TCK likewise only covers such scenario, see https://github.com/eclipse-ee4j/cdi-tck/tree/master/impl/src/main/java/org/jboss/cdi/tck/tests/event/observer/async/handlingExceptions

We should change the chapter title to something like `Handling exceptions thrown during an asynchronous event` and in the text we need to either explicitly state that the cause is always `CompletionException` or just mention what happens in case there is only one exception.

Afterwards, we should add a TCK test for it.

Note that this was originally brought up in Quarkus issue - https://github.com/quarkusio/quarkus/issues/24646

**Comment by Ladicek** [comment]
I agree that we should get rid of the word "multiple" in the name of the section, but "CompletionException contains all exceptions thrown by observers as suppressed exceptions" is IMHO completely clear in what should happen if only one exception occurs.

**Comment by manovotn** [comment]
@Ladicek I see it the same way but in the least we should add a TCK test that asserts it. I have create all the needed issues so it hopefully won't be forgotten :)

**Comment by Ladicek** [comment]
Yea totally agree about the TCK.

**Comment by Emily-Jiang** [comment]
Does this require another respin of the release? If yes, I will need to withdraw the ballot again. please let me asap.

**Comment by starksm64** [comment]
No as this is not a new issue. It is simply additional test coverage that can be rolled into the next TCK update.
