### ISSUE TITLE
Contradicting statements in `Built-in qualifier types`

### ISSUE THREAD

**Issue by dstepanov** [eclipse-ee4j/cdi#602]
[Built-in qualifier types](https://github.com/eclipse-ee4j/cdi/blob/12047eec5abd754c2927d52f147d57b5b7098022/spec/src/main/asciidoc/core/definition.asciidoc#built-in-qualifier-types) section defines:

> If a bean does not explicitly declare a qualifier other than `@Named` or `@Any`, the bean has exactly one additional qualifier, of type `@Default`. This is called the default qualifier.

And then the following:

> The following declaration results in a bean with three qualifiers: `@Any`, `@Default` and `@Named("ord")`.
> 
> ```java
> @Named("ord")
> public class Order { ... }
> ```

My understanding from the first statement is that `@Default` shouldn't be added if `@Named` is present.
Which makes sense otherwise you cannot inject not named bean candidate.

**Comment by manovotn** [comment]
The sentence is correct albeit not easy to read. Mind the collocations `other than` and `one additional`.

> If a bean does not explicitly declare a qualifier **_other than_** `@Named` or `@Any`, the bean has exactly **_one additional_** qualifier, of type `@Default`

Simplified meaning would be:

> if a bean has only `@Named` or `@Any` qualifiers, add `@Default` as well

This basically makes sure that beans with custom qualifiers (anything else than `@Named` and `@Any`) won't be `@Default` as well and hence won't match un-annotated injection points (such as plain `@Inject Bar`).

> Which makes sense otherwise you cannot inject not named bean candidate.

I am sorry but I don't get what you mean here?

**Comment by dstepanov** [comment]
Yeah, It makes sense. 
Can I have multiple named beans and one not named bean? How can I inject the one without the named annotation? The default qualifier is present on all of them.

**Comment by manovotn** [comment]
> Yeah, It makes sense. Can I have multiple named beans and one not named bean? How can I inject the one without the named annotation? The default qualifier is present on all of them.

Correct observation. The `@Named` qualifier gets special treatment by CDI (which is also the reason why it shouldn't be used as common differentiating qualifier).
To answer you, that would result in ambiguous resolution and you'd need to add qualifier to them or inject them by exact type - assuming the impl type differs.

**Comment by dstepanov** [comment]
Thanks for the clarification.
