### ISSUE TITLE
Missing dependency jakarta.el:jakarta.el-api.jar:5.0.0 ?

### ISSUE THREAD

**Issue by hjohn** [eclipse-ee4j/cdi#606]
The jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.0 seems to depend on jakarta.el:jakarta.el-api.jar:5.0.0 which is not in Maven Central. The 4.0.0-RC5 release had no such problems. Is this an oversight or am I doing something wrong?

**Comment by manovotn** [comment]
@hjohn You are not doing anything wrong, EL JAR is not yet released, only staged.

EL API JAR was staged and in ballot even before CDI was but apparently they did a re-spin and CDI got ahead.
The ballot was supposed to end sometime this week but I am not sure exactly when.

**Comment by punkratz312** [comment]
yes im facing the same issue:

'''
Execution failed for task ':executor:compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':executor:compileKotlin'
   > Could not resolve all files for configuration ':executor:compileClasspath'.
      > Could not find jakarta.el:jakarta.el-api:5.0.0.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/jakarta/el/jakarta.el-api/5.0.0/jakarta.el-api-5.0.0.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            project :executor > jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.0
'''

5.0.0 is referenced but was not released yet....

https://mvnrepository.com/artifact/jakarta.enterprise/jakarta.enterprise.cdi-api/4.0.0

**Comment by manovotn** [comment]
According to the ballot progress document[1], EL ballot ends on May 9.
Nothing much we can do up until then, so I'll close this issue.

[1] https://docs.google.com/spreadsheets/d/1YTUpfdLZZrk2_UGwoX2w0seOCueRO3sQJIjWxpDAa7g/edit#gid=35969432
