### ISSUE TITLE
org.jboss.cdi.tck.tests.full.deployment.exclude.ExcludeFiltersTest#testExcludeSystemPropertyActivator overrides the 

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi#607]
The ExcludeFiltersTest has the following groups config:

```java
package org.jboss.cdi.tck.tests.full.deployment.exclude;

@SpecVersion(spec = "cdi", version = "2.0")
@Test(groups = CDI_FULL)
public class ExcludeFiltersTest extends AbstractTest {
...
    @Test(groups = { INTEGRATION, SYSTEM_PROPERTIES })
    @SpecAssertions({ @SpecAssertion(section = EXCLUDE_FILTERS, id = "d"), @SpecAssertion(section = EXCLUDE_FILTERS, id = "e") })
    public void testExcludeSystemPropertyActivator() {
...
    }
```

The https://testng.org/doc/documentation-main.html#test-groups does not make it clear how these annotations combine, but apparently the method level overrides the class level because when running with the CDI_FULL group excluded, the testExcludeSystemPropertyActivator method is run.

We will need to add the CDI_FULL group to the method as well.

**Comment by Ladicek** [comment]
Makes sense to me.

**Comment by manovotn** [comment]
Will send a PR.
BTW future challenges should IMO be tracked under the TCK repository.
